### ISSUE TITLE
Firmware Flashing fails

### ISSUE THREAD

**Issue by whoot** [RCayre/mirage#1]
Hey,

I was trying to flash the firmware 'btlejack-firmware-microbit.hex' from https://redmine.laas.fr/projects/btlejack-custom-firmware/repository to the Micro:bit.
However, it didn´t work and all i get is a textfile FAIL.TXT in the micro:bit folder which states:
```
In application programming write failed.
```

What am i doing wrong?

**Comment by RCayre** [comment]
Hello,
This issue has already been mentionned here: 
https://github.com/virtualabs/btlejack-firmware/issues/8

The reason remains unknown, however the problem seems to be "solved" by flashing a genuine microbit firmware before trying with btlejack.

When you plug the micro:bit, does it appears as an USB mass storage device ?

**Comment by whoot** [comment]
Hi,

thanks for your response. Not pressing the reset button worked!
Maybe you should mention that somewhere in the Readme.

Thanks for your help!

**Comment by RCayre** [comment]
Good.
I'll release a new version soon, so I'll probably add it to the readme and the documentation. Thanks for reporting this issue.
