### ISSUE TITLE
Add [global] section in mirage.cfg

### ISSUE THREAD

**Issue by whoot** [RCayre/mirage#3]
It would be great if you could add a [global] section in the configuration file _mirage.cfg_ which is then used by every module to adopt new default values.

This would be especially helpful for INTERFACES, because you don't have to define them per module every time.

Example:
```
[global]
INTERFACE = microbit0
INTERFACEA = microbit1
INTERFACEB = microbit2
```

**Comment by RCayre** [comment]
Hi, 
in my opinion, it's not really interesting to add this kind of features, because some modules aren't supposed to work with all the supported devices. As an example, ble_jam is not compatible with a HCI device and ble_connect can't be used with a microbit flashed with the BTLEJack firmware.

However, it could be interesting to provide a way to configure multiple modules with only one entry in the configuration file. Maybe it could be based on the technology or type attributes of the modules.

I close this issue temporarly, I'll reopen it if I decide to include something similar.
